[package]
name = "euler-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hazs_tools = { git = "https://github.com/haz0110/hazs_tools" }  
primes = "0.3.0"
